name: Eslint
on:
  push:
    branches:
      - 'main'
    paths:
      - '**/*.js'

jobs:
  pipeline:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - run: npm ci
      - run: npm run lint